# Generated by Django 4.0.3 on 2022-04-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total',
            name='area',
        ),
        migrations.AddField(
            model_name='total',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myadmin.category'),
            preserve_default=False,
        ),
    ]
